### ISSUE TITLE
Record Played Game Page Should Validate For Existence of At Least 1 Game Definition

### ISSUE THREAD

**Issue by jakejgordon** [jakejgordon/NemeStats#133]
If you go to the Record Played Game page and enter a bunch of player ranks it is really frustrating to discover that you don't have any game definitions created -- and it isn't obvious what the user should do. Need to solve this.

New Idea:
1) user goes to record a game with no game definnitions defined
2) message displays indicating that they haven't set up a game definition yet, and they can click the following link to do so: <link here>
3) they click the link, it takes them to /GameDefinition/Create?returnUrl=recordGame
4) user starts typing a game and picks one from the auto-complete box
Now
Jake Gordon
Dennis Silva
5) user  clicks save and is redirected back to the /PlayedGame/Create page with ?gameDefinitionId=X in the query string, where X is the newly created game definition
6) the record a game page has that newly created game definition pre-selected in the drop-down

**Comment by jakejgordon** [comment]
Copy/paste of G+ conversation for reference as to why I'm pulling it back into progress:

 I think the little popup thingy is OK in terms of telling the user what to do, but I'm thinking we should block them from doing anything on the page and give them the option to go back and create a game definition. The real problem is that users go to this page after just creating a gaming group, they add some players and set their ranks, and then only after hitting "Create" do they realize it was all for naught and they have to leave the page to go create a game definition, and then do it all over.
I'm really not sure the best way to do it. Maybe just a red message at the top of the form with the entire form disabled?
I'm open to ideas.

**Comment by dsilva609** [comment]
Now when there are no game definitions, it disables the form input controls and has  a link to create a new game definition

**Comment by jakejgordon** [comment]
Need to link to /GameDefinition/Create and wire this page up to the auto-select. It should redirect back to the played game page with this game defintion automatically selected.
