### ISSUE TITLE
Ability to flag game as "Everyone lost" or "Everyone Won"

### ISSUE THREAD

**Issue by jakejgordon** [jakejgordon/NemeStats#144]
Users are struggling with the manual entry of game ranks and don't realize they can manually set the ranks of players to be identical (e.g. everyone gets 2nd place because they lost or everyone won). We should add either a radio button to change the entry mode or possibly add different buttons for "Record Game" vs. "Everyone Won" vs. "Everyone Lost" or something like that. We may want a tooltip as well.

Since it already supports this by setting everyone to rank of 2nd place, just need to provide a shortcut to doing this in the UI. I (Jake) will go ahead and update the places where it shows game rank to just say "Everyone lost" or "Everyone Won" if all ranks are non-1 or all-1, respectively.

**Comment by Tuxedoian** [comment]
Yeah, it would be helpful for games like Arkham Horror or Shadows of Brimstone or Pandemic, if we had a radio button or something to denote that the game was a co-op, and we either completed the objective, or whether the game stomped us flat.
