### ISSUE TITLE
Minor UI Enhancements to Record a Game Screen

### ISSUE THREAD

**Issue by jakejgordon** [jakejgordon/NemeStats#161]
Need to make a few minor enhancements to the record a game screen:
- Make the Rank box look like a text box and different from the other buttons
- Use the ellipsis style instead of trunking the name/rank text on each player item.

**Comment by jakejgordon** [comment]
Addressed the 'X' portion of the story on a different card. Eliminated that from the description.

**Comment by dsilva609** [comment]
Probably will need to be tested on all current browers

**Comment by jakejgordon** [comment]
Tosho says line-height is the style to help realign the buttons next to a player
